on:
  - push
  - pull_request

jobs:
  compile-examples:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn:
          - arduino:avr:nano

    steps:
      - uses: actions/checkout@v3
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}

          sketch-paths: |
            - examples/Shellminator_execute

  compile-examples-commander:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn:
          - arduino:avr:nano

    steps:
      - uses: actions/checkout@v3
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}

          sketch-paths: |
            - examples/Shellminator_Commander

          libraries: |
            - name: Shellminator
