on:
  - push
  - pull_request

jobs:
  compile-examples:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn:
          - arduino:avr:uno
          - arduino:avr:nano
          - arduino:avr:mega
          - arduino:avr:leonardo
          - arduino:avr:micro
          - arduino:avr:mini

    steps:
      - uses: actions/checkout@v3
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}

          sketch-paths: |
            - examples/Shellminator_execute
            - examples/Shellminator_simple

  compile-examples-for-esp32:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        fqbn:
          - esp32:esp32:esp32
          - esp32:esp32:esp32s3
          - esp32:esp32:esp32c3

    steps:
      - uses: actions/checkout@v3
      - uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.fqbn }}

          platforms: |
            - name: esp32:ESP32
              source-url: https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json

          sketch-paths: |
            - examples/Shellminator_execute
            - examples/Shellminator_simple
